!!python/object/new:box.box.Box
dictitems:
  batch_size: 64
  build_model: !!python/object/new:box.box.Box
    dictitems:
      loss: sparse_categorical_crossentropy
      metrics: !!python/object/new:box.box_list.BoxList
        listitems:
        - accuracy
        state:
          box_options:
            box_class: &id001 !!python/name:box.box.Box ''
            box_dots: false
            box_duplicates: ignore
            box_intact_types: !!python/tuple []
            box_namespace: !!python/tuple
            - build_model
            - metrics
            box_recast: null
            box_safe_prefix: x
            camel_killer_box: false
            conversion_box: true
            default_box: false
            default_box_attr: *id001
            default_box_create_on_get: true
            default_box_none_transform: true
            frozen_box: false
            modify_tuples_box: false
          box_org_ref: 140274295789696
      optimizer: adam
      summary: false
    state:
      _box_config:
        __created: true
        __safe_keys:
          loss: loss
          metrics: metrics
          optimizer: optimizer
          summary: summary
        box_class: *id001
        box_dots: false
        box_duplicates: ignore
        box_intact_types: !!python/tuple []
        box_namespace: !!python/tuple
        - build_model
        box_recast: null
        box_safe_prefix: x
        camel_killer_box: false
        conversion_box: true
        default_box: false
        default_box_attr: *id001
        default_box_create_on_get: true
        default_box_none_transform: true
        frozen_box: false
        modify_tuples_box: false
  csv_dir: ./
  dataset_dir: ./
  dataset_name: casia
  epochs: 500
  freeze_epochs: 500
  image_shape: !!python/object/new:box.box_list.BoxList
    listitems:
    - 280
    - 320
    - 3
    state:
      box_options:
        box_class: *id001
        box_dots: false
        box_duplicates: ignore
        box_intact_types: !!python/tuple []
        box_namespace: !!python/tuple
        - image_shape
        box_recast: null
        box_safe_prefix: x
        camel_killer_box: false
        conversion_box: true
        default_box: false
        default_box_attr: *id001
        default_box_create_on_get: true
        default_box_none_transform: true
        frozen_box: false
        modify_tuples_box: false
      box_org_ref: 140274295751552
  output_path: ./reports
  project_name: ml-iris-tf
  random_seed: 42
  shuffle_train: true
  start_epoch: 0
  sync_tensorboard: true
  test_size: 0.333
  train_size: 0.667
  wandb: !!python/object/new:box.box.Box
    dictitems:
      dataset_name: casia
      log: all
      log_model: true
      log_preds: false
    state:
      _box_config:
        __created: true
        __safe_keys:
          dataset_name: dataset_name
          log: log
          log_model: log_model
          log_preds: log_preds
        box_class: *id001
        box_dots: false
        box_duplicates: ignore
        box_intact_types: !!python/tuple []
        box_namespace: !!python/tuple
        - wandb
        box_recast: null
        box_safe_prefix: x
        camel_killer_box: false
        conversion_box: true
        default_box: false
        default_box_attr: *id001
        default_box_create_on_get: true
        default_box_none_transform: true
        frozen_box: false
        modify_tuples_box: false
state:
  _box_config:
    __created: true
    __safe_keys:
      batch_size: batch_size
      build_model: build_model
      csv_dir: csv_dir
      dataset_dir: dataset_dir
      dataset_name: dataset_name
      epochs: epochs
      freeze_epochs: freeze_epochs
      image_shape: image_shape
      output_path: output_path
      project_name: project_name
      random_seed: random_seed
      shuffle_train: shuffle_train
      start_epoch: start_epoch
      sync_tensorboard: sync_tensorboard
      test_size: test_size
      train_size: train_size
      wandb: wandb
    box_class: *id001
    box_dots: false
    box_duplicates: ignore
    box_intact_types: !!python/tuple []
    box_namespace: !!python/tuple []
    box_recast: null
    box_safe_prefix: x
    camel_killer_box: false
    conversion_box: true
    default_box: false
    default_box_attr: *id001
    default_box_create_on_get: true
    default_box_none_transform: true
    frozen_box: false
    modify_tuples_box: false
